language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t iansand/docker-react -f Dockerfile.dev . 
    
script:
    - docker run -e CI=true iansand/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker-react"
    env: "DockerReact-env"
    bucket_name: "elasticbeanstalk-eu-west-1-856509520645"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY