language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t iansand/docker-react -f Dockerfile.dev . 
    
script:
    - docker run -e CI=true iansand/docker-react npm run test